### ISSUE TITLE
pb importing VIP module

### ISSUE THREAD

**Issue by epantin** [vortex-exoplanet/VIP#435]
After a fresh install of python 3.6 on mac os, I could not have vip to work (see below). 
I found that the problem comes from photutils, which has different dependences than vip, it needs higher versions
of astropy and numpy. After installing these ones, I could import vip 

>>> import vip_hci as vip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/vip_hci/__init__.py", line 3, in <module>
    from . import andromeda
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/vip_hci/andromeda/__init__.py", line 3, in <module>
    from .andromeda import *
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/vip_hci/andromeda/andromeda.py", line 27, in <module>
    from ..var.filters import frame_filter_highpass, cube_filter_highpass
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/vip_hci/var/__init__.py", line 11, in <module>
    from .fit_2d import *
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/vip_hci/var/fit_2d.py", line 16, in <module>
    import photutils
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/photutils/__init__.py", line 19, in <module>
    from .aperture import *  # noqa
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/photutils/aperture/__init__.py", line 7, in <module>
    from .circle import *  # noqa
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/photutils/aperture/circle.py", line 13, in <module>
    from .core import PixelAperture, SkyAperture
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/photutils/aperture/core.py", line 104, in <module>
    class PixelAperture(Aperture):
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/photutils/aperture/core.py", line 369, in PixelAperture
    subpixels=5, unit=None):
  File "/Users/Eric/Softs/Python/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 445, in decorator
    '.'.format(new_name[i]))
TypeError: "None" was not specified in the function signature. If it was meant to be part of "**kwargs" then set "arg_in_kwargs" to "True".
--

**Comment by VChristiaens** [comment]
Thanks @epantin. I have now adapted the astropy and numpy versions in the requirements text file to allow for a smooth installation from scratch.
