### ISSUE TITLE
Issue with importing vip module after installation

### ISSUE THREAD

**Issue by apchsh** [vortex-exoplanet/VIP#444]
After installing VIP using pip, on python 3.6.8, I got the error message below when trying to import the package. It seems that bokeh-1.4.0 was installed automatically via pip, but a higher version is needed. Updating bokeh resolved the issue.    

```
Traceback (most recent call last):
  File "sdi.py", line 3, in <module>
    import vip_hci as vip
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/vip_hci/__init__.py", line 3, in <module>
    from . import andromeda
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/vip_hci/andromeda/__init__.py", line 3, in <module>
    from .andromeda import *
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/vip_hci/andromeda/andromeda.py", line 27, in <module>
    from ..var.filters import frame_filter_highpass, cube_filter_highpass
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/vip_hci/var/__init__.py", line 11, in <module>
    from .fit_2d import *
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/vip_hci/var/fit_2d.py", line 17, in <module>
    from hciplot import plot_frames
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/hciplot/__init__.py", line 3, in <module>
    from .hciplot import plot_frames, plot_cubes
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/hciplot/hciplot.py", line 8, in <module>
    import holoviews as hv
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/holoviews/__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/holoviews/annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/__init__.py", line 3, in <module>
    from . import layout # noqa
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/layout/base.py", line 13, in <module>
    from ..io.model import hold
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/io/__init__.py", line 8, in <module>
    from ..config import config
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/config.py", line 20, in <module>
    from .io.notebook import load_notebook
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/io/notebook.py", line 43, in <module>
    from .server import _server_url, _origin_url, get_server
  File "/home/alex/Documents/faint_bls3/lib/python3.6/site-packages/panel/io/server.py", line 25, in <module>
    from bokeh.embed.bundle import extension_dirs
ImportError: cannot import name 'extension_dirs'``
```

**Comment by VChristiaens** [comment]
I was not able to reproduce the issue in a new python 3.6.8 conda environment - pip automatically installed holoviews 1.13.2 and then bokeh 2.0.1 for me, upon pip install of vip-hci. Was an older version of holoviews already present in your environment by any chance?

Note that the issue is in the requirements for hciplot rather than in VIP. The best is probably to either raise an issue in that github or propose a pull request to change the requirement file there if you have identified that stricter package version requirements were necessary.

**Comment by apchsh** [comment]
Thanks, I'll have a look at the requirements for hciplot
